### ISSUE TITLE
ControlNet not working properly

### ISSUE THREAD

**Issue by pinacolad** [mix1009/sdwebuiapi#24]
When using `controlnet_units` in sdwebuiapi there seems to be a thing not working for me.

My code is as following:
```python
test_image = Image.open('in/in_1.png')

depth_model = 'control_sd15_depth [fef5e48e]'

cn_depth_unit = webuiapi.ControlNetUnit(
    input_image=test_image,
    model=depth_model,
    module='depth',
    )

r2 = api.img2img(
            prompt="something",
            images=[test_image], 
            width=512,
            height=512,
            controlnet_units=[cn_depth_unit],
            sampler_name="Euler a",
            cfg_scale=7,
           )
```

The sdwebuiapi error is as following:
```
Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Desktop\no_where\main.py", line 31, in <module>
    r2 = api.img2img(
  File "C:\Users\xxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webuiapi\webuiapi.py", line 351, in img2img
    return self.custom_post('controlnet/img2img', payload=payload)
  File "C:\Users\xxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webuiapi\webuiapi.py", line 522, in custom_post
    return self._to_api_result(response)
  File "C:\Users\xxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webuiapi\webuiapi.py", line 139, in _to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (500, 'Internal Server Error')
```

The Automatic1111 error is as following:
```
 Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\xxxxxxxx\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 285, in img2img
    cn_image = Image.open(io.BytesIO(base64.b64decode(controlnet_input_image[0])))
```

**Comment by mix1009** [comment]
Looks like it might be a memory problem.

Resize the image.
```
test_image = test_image.resize((512,512))
```

using fp16 based model should also decrease memory footprint.
https://huggingface.co/webui/ControlNet-modules-safetensors

**Comment by pinacolad** [comment]
Resizing the image does not seem to work for me. Using the `control_depth-fp16 [400750f6]` model does also not work. It looks like the issue occurs in the api itself. Anyone else having this issue?

**Comment by pinacolad** [comment]
I see I did not update my controlnet extension. Updating it helped the job.
