### ISSUE TITLE
Where should I put the "clip_skip" and "ENSD" parameters?

### ISSUE THREAD

**Issue by agansama** [mix1009/sdwebuiapi#27]
Hi, when I tried using the following command
```
api = webuiapi.WebUIApi(host='127.0.0.1',port=7860,sampler='DPM++ 2M Karras',steps=20)
result2=api.txt2img(
	enable_hr=True,
	firstphase_width=512,
	firstphase_height=512,
	hr_scale=2,
	hr_upscaler="Lanczos",
	hr_second_pass_steps=11,
	hr_resize_x=1024,
	hr_resize_y=1024,
	prompt="a dog",
	seed=-1,
	cfg_scale=7.0,
	negative_prompt="ugly,out of frame",
	override_settings={"clip_skip":2,"ENSD":31337},
)
```
Program throws this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\python38\lib\site-packages\webuiapi\webuiapi.py", line 257, in txt2img
    return self._to_api_result(response)
  File "E:\python38\lib\site-packages\webuiapi\webuiapi.py", line 139, in _to_api_result
    raise RuntimeError(response.status_code, response.text)
RuntimeError: (500, 'Internal Server Error')
```
When I try to set override to a null value like this，The program can run correctly
```
result2=api.txt2img(
	enable_hr=True,
	firstphase_width=512,
	firstphase_height=512,
	hr_scale=2,
	hr_upscaler="Lanczos",
	hr_second_pass_steps=11,
	hr_resize_x=1024,
	hr_resize_y=1024,
	prompt="a dog",
	seed=-1,
	cfg_scale=7.0,
	negative_prompt="ugly,out of frame",
	override_settings={},
)
```
I'm new to webuiapi, and based on my GUI experience simply think these two parameters should be passed in override_settings.But it's not what I expected.Where should I put the "clip_skip" and "ENSD" parameters?
Looking forward to your reply。

**Comment by agansama** [comment]
The above is an exception thrown by the webui api module when I operate in python. This is an error that occurs on the command line at the same time. I hope it will help.
```
Traceback (most recent call last):
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/newsdc/mfz/webui/stable-diffusion-webui/modules/api/api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/mfz/miniconda3/envs/webui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/newsdc/mfz/webui/stable-diffusion-webui/modules/api/api.py", line 203, in text2imgapi
    processed = process_images(p)
  File "/home/newsdc/mfz/webui/stable-diffusion-webui/modules/processing.py", line 474, in process_images
    stored_opts = {k: opts.data[k] for k in p.override_settings.keys()}
  File "/home/newsdc/mfz/webui/stable-diffusion-webui/modules/processing.py", line 474, in <dictcomp>
    stored_opts = {k: opts.data[k] for k in p.override_settings.keys()}
KeyError: 'clip_skip'
```

**Comment by mix1009** [comment]
I have no idea. I've browsed the webui code... I don't think it's exposed to the api.

**Comment by sicp-dnegvp** [comment]
I don't know how to set ENSD, but you had the right idea for clip skip, it goes into override_settings, just with a different key name:
```
override = {}
override["CLIP_stop_at_last_layers"] = 2
api.txt2img(....,
		override_settings = override
)
```

**Comment by agansama** [comment]
I guess I haven't researched the site http://127.0.0.1:7860/docs#/  enough,Thank you very much for your replies, it worked very well.

**Comment by agansama** [comment]
> You had the right idea, it goes into override_settings, just with a different key name:
> 
> ```
> override = {}
> override["CLIP_stop_at_last_layers"] = 2
> override["eta_noise_seed_delta"] = 31337
> api.txt2img(....,
> 		override_settings = override
> )
> ```
> 
> Check in the webui API docs for what else can go in there (while it's running): http://127.0.0.1:7860/docs#/default/get_config_sdapi_v1_options_get

I guess I haven't researched the site http://127.0.0.1:7860/docs#/ enough,Thank you very much for your replies, it worked very well.
