### ISSUE TITLE
Unable to send requests to custom host

### ISSUE THREAD

**Issue by spenceralbrecht** [mix1009/sdwebuiapi#41]
I have created the client as follows `api = webuiapi.WebUIApi(host='http://150.230.46.7', port=7860)` but I am getting the following error
```
python client.py
Traceback (most recent call last):
  File "/home/spencera/stable-diffusion-playground/sdwebuiapi/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/spencera/stable-diffusion-playground/sdwebuiapi/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/spencera/.pyenv/versions/3.8.10/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by spenceralbrecht** [comment]
I realized the issue was passing `http://` with the host when it should have just been the IP address.
